# .kodiak.toml
version = 1

[merge]

automerge_label = "automerge"
blacklist_title_regex = "^WIP.*"
blacklist_labels = ["wip"]
method = "rebase"
delete_branch_on_merge = true
block_on_reviews_requested = true